### PR TITLE
JS authentication feature

### PR DESCRIPTION
**Pull request by JeffreySpitz**
This Pull Request Implements the Authentication Feature
Pivotal Tracker ID #152339680

Pull Request Details:
**Visually**
- Users can now log in and out of the breathe cal site

**Codewise**
- We use the gem 'omniauth-google-oauth2' for login functionality
- Cucumber and RSpec tests use omniauth stubs to simulate logging in without calling Google API
- Updated Users model to require name, email, uid, token, and other fields as well as check for a valid token expiration date
- Removed the security risk create_dummy action in sessions controller that bypassed omniauth checks and allowed for creation of any user record.
- Refactored User model and Session controller to be more DRY
- Edited index.html so authentication failures are displayed to the user in red text.

### CODE REVIEW

**Review by deduq2 — APPROVED** [review]
LGTM,
Great addition of the flash for failed login
Extensive new test structure - wow!
Good stuff with the user model, esp. abstracting pulling data from the hash to the method auth_data

**Comment by Steven9** [comment]
Nice job on user model update!
It's nice to remove create_dummy so we dont have to worry about potential danger of bypassing omniAuth.

**Review by tinhnguyen20 — COMMENTED** [review]
Good work on setting up omni-authentication for users and adding redirects for seamless use of app!

**Review by MaadhavShah — APPROVED** [review]

**Review by Steven9 — COMMENTED** [review]
Nice job on user model update!
It's nice to remove create_dummy so we dont have to worry about potential danger of bypassing omniAuth.

**Pull request merged**
